print("Olá turma do Python!")
print("Tudo joia!")
nome: str = input("Qual é o seu nome? ")
print(f"Olá, {nome}!")
idade = int(input("Qual a sua idade? "))
print(f"{nome} a sua idade é {idade} anos")
cidade = str(input("Você é de qual cidade ?"))
print(f"Sua cidade atual é {cidade}! ")
