print("Olá turma do Python!")
print("Tudo joia!")
nome: str = input("Qual é o seu nome? ")
print(f"Olá, {nome}!")
idade = int(input("Qual a sua idade? "))
print(f"Olá {nome}, sua idade é {idade} anos")
